### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by Botspot** [thenumbernine/sand-tetris#2]
I am still interested in adding this to our [ARM Linux app store](https://pi-apps.io), however your readme does not adequately explain how one is to actually compile and install this program.
In issue #1, you mention that other repos listed in the readme need to be "added". How? Where? Do I need to git clone all of those repos to my home directory and then the main sand-tetris project will work?
What build tools are needed? How are you building your github release on, and with what commands?

You mentioned that you might upload an example build script. Is that still being worked on?
If the answer to my questions above is "just learn it all and figure it out yourself", then my response will be something like "I have hundreds of other apps to worry about in the app store I maintain, and I cannot afford to spend a week trying to understand one person's poorly documented work."

**Comment by thenumbernine** [comment]
In light of the contrast between the title and the message, how about I either 
1) rename this to "Installing on ARM" and we can focus on that,
2) close this, since this is a LuaJIT project, there is no compiling involved, and maybe you can add this as a comment to the first issue of "installation instructions" in general.

Your hurdle is compiling the LuaJIT code for ARM, this is going to have little to nothing to do with the SandTetris code.  I can walk you through this at least on Android SDK (which I've done before), but that has nothing to do with SandTetris and will ultimately be a fully different repo of Android+JNI+SDL+LuaJIT code (which I have sitting on my computer from about 10 years ago, collecting dust).

**Comment by Botspot** [comment]
I think my confusion here is not understanding what LuaJIT is.
Closing this issue for now, though I may want to reopen it once I have LuaJIT installed.

**Comment by thenumbernine** [comment]
I don't have a Raspberry PI handy so I can't mess around with building LuaJIT on Raspberry PI, but that would be the basics of getting this running.

Or if there is a package manager for it, (I'm not sure, and not sure what packages it would have), maybe it will be as easy as simply installing a luajit package and a package for each of the libraries that I listed in the first issue.

If you can do this then the only challenge left would be to make sure the library/runtime paths are all set up correctly, and that could be as simple as downloading the linux release of sandtetris and replacing the x64 luajit/so's with equivalent ones for ARM.

Worst case, the libraries have different names and you have to edit the code to reflect that as well.

**Comment by thenumbernine** [comment]
I installed raspberry pi os via QEMU and am testing things out.
I'm following this tut: https://linuxconfig.org/how-to-run-the-raspberry-pi-os-in-a-virtual-machine-with-qemu-and-kvm
Looks like LuaJIT and SDL are pre-installed / apt packages, so that much should be easy to set up.
The only big challenge was that, in Pi, the shared libraries were all using the .so.<version> naming convention -- there were no just .so that were symbolically-linked to the .so.<version> as is on my Ubuntu machine -- and for this reason LuaJIT's ffi.load() function doesn't find them unless you specify the exact name.
So once I gave the ffi.load() functions the correct library names as they are on Pi, everything worked fine ...

... up until I got to ImGui.  That's turning out to be some teeth pulling.  I might upgrade my own ImGui support to the latest in hope that resolves any of the problems.
